const tools=[["Word Counter","Writing","Count words, characters and reading time."],["Character Counter","Writing","Count characters quickly."],["Case Converter","Writing","Transform text into useful cases."],["Reading Time Calculator","Writing","Estimate reading time."],["Percentage Calculator","Calculators","Calculate percentages and changes."],["Age Calculator","Calculators","Calculate an exact age."],["Average Calculator","Calculators","Find an average."],["Discount Calculator","Calculators","Work out discounts."],["Date Difference Calculator","Calculators","Compare two dates."],["JSON Formatter","Developer","Make JSON readable."],["JSON Validator","Developer","Check JSON syntax."],["Base64 Encoder","Developer","Encode and decode Base64."],["URL Encoder","Developer","Encode and decode URL values."],["Color Converter","Developer","Convert common color formats."],["QR Code Generator","Generators","Generate a QR code."],["Password Generator","Security","Create strong passwords."],["Random Number Picker","Generators","Pick a random number."],["Image Compressor","Images","Reduce image file size."],["Image Resizer","Images","Resize images."],["Countdown Timer","Time","Create a countdown."],["Unit Converter","Converters","Convert common units."]];
const body=document.body,search=document.getElementById("search"),results=document.getElementById("results");
if(localStorage.getItem("sot-theme")==="light")body.classList.add("light");
document.getElementById("theme").onclick=()=>{body.classList.toggle("light");localStorage.setItem("sot-theme",body.classList.contains("light")?"light":"dark")};
document.getElementById("menu").onclick=()=>document.getElementById("mobile").classList.toggle("open");
function render(q){q=q.toLowerCase().trim();if(!q){results.classList.remove("open");return}let m=tools.filter(t=>t.join(" ").toLowerCase().includes(q)).slice(0,6);results.innerHTML=m.length?m.map(t=>`<a class="result" href="#tools"><span><b>${t[0]}</b><small>${t[1]} · ${t[2]}</small></span>↗</a>`).join(""):`<div class="result"><span><b>No matching tool yet</b><small>Try word, JSON, QR, percentage or image.</small></span></div>`;results.classList.add("open")}
search.oninput=e=>render(e.target.value);
document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement!==search){e.preventDefault();search.focus()}});
document.addEventListener("click",e=>{if(!e.target.closest("#searchbox"))results.classList.remove("open")});
document.querySelectorAll("[data-tool]").forEach(x=>x.onclick=e=>{e.preventDefault();search.value=x.dataset.tool;render(x.dataset.tool);search.focus()});
const demo=document.getElementById("demo");function count(){let t=demo.value,w=t.trim()?t.trim().split(/\s+/).length:0;document.getElementById("words").textContent=w;document.getElementById("chars").textContent=t.length;document.getElementById("time").textContent=(w?Math.max(1,Math.ceil(w/200)):0)+" min"}demo.oninput=count;count();document.getElementById("year").textContent=new Date().getFullYear();